services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriptions
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./internal/db/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql
  
  subscriptions-service:
    build: 
      context: .
    command: ["./subscriptions-service"]
    ports: 
      - "8080:8080"
      - "2112:2112"
    depends_on:
      - postgres
    env_file:
      - .env

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - subscriptions-service

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  pg_data:
  grafana_data: